import type { FilterDefinition } from "./types";

/**
 * Bundled movie-style filter presets. Each preset combines color-adjustment
 * deltas (full strength, neutral 0) with an optional bundled 3D LUT. The LUT
 * ids match `app/src/effects/lut/bundled-luts.ts`.
 */
export const FILTER_PRESETS: FilterDefinition[] = [
	{
		id: "teal-orange",
		name: "Teal & Orange",
		category: "Color",
		keywords: ["teal", "orange", "blockbuster", "hollywood"],
		adjust: { contrast: 8, saturation: 12 },
		lutId: "teal-orange",
	},
	{
		id: "warm-film",
		name: "Warm Film",
		category: "Film",
		keywords: ["warm", "film", "sunset", "kodak"],
		adjust: { temperature: 15, saturation: 8 },
		lutId: "warm-film",
	},
	{
		id: "cool-night",
		name: "Cool Night",
		category: "Mood",
		keywords: ["cool", "night", "blue", "noir"],
		adjust: { temperature: -15, contrast: 5 },
		lutId: "cool",
	},
	{
		id: "bleach-bypass",
		name: "Bleach Bypass",
		category: "Film",
		keywords: ["bleach", "bypass", "gritty", "contrast"],
		adjust: { contrast: 15, saturation: -20 },
		lutId: "bleach-bypass",
	},
	{
		id: "noir-bw",
		name: "Noir B&W",
		category: "Black & White",
		keywords: ["noir", "black and white", "mono", "bw"],
		adjust: { contrast: 20, exposure: -5 },
		lutId: "black-and-white",
	},
	{
		id: "faded-matte",
		name: "Faded Matte",
		category: "Film",
		keywords: ["faded", "matte", "muted", "flat"],
		adjust: { contrast: -15, shadows: 15, saturation: -8 },
		lutId: "faded",
	},
	{
		id: "vivid",
		name: "Vivid",
		category: "Color",
		keywords: ["vivid", "punchy", "saturated", "pop"],
		adjust: { saturation: 35, contrast: 15 },
	},
	{
		id: "sepia",
		name: "Sepia",
		category: "Color",
		keywords: ["sepia", "old", "vintage", "antique"],
		adjust: { contrast: 5 },
		lutId: "sepia",
	},
	{
		id: "cross-process",
		name: "Cross Process",
		category: "Film",
		keywords: ["cross", "process", "lomo", "experimental"],
		adjust: { contrast: 15, saturation: 20 },
		lutId: "cross-process",
	},
	{
		id: "day-for-night",
		name: "Day for Night",
		category: "Mood",
		keywords: ["day for night", "night", "moonlight", "blue"],
		adjust: { exposure: -20, temperature: -20, saturation: -15 },
		lutId: "day-for-night",
	},
	{
		id: "portra-ish",
		name: "Portra-ish",
		category: "Film",
		keywords: ["portra", "skin", "soft", "film"],
		adjust: { temperature: 12, contrast: -10, saturation: 5, shadows: 8 },
	},
	{
		id: "kodachrome-ish",
		name: "Kodachrome-ish",
		category: "Film",
		keywords: ["kodachrome", "rich", "saturated", "film"],
		adjust: { contrast: 18, saturation: 25, temperature: 8 },
	},
	{
		id: "pastel",
		name: "Pastel",
		category: "Color",
		keywords: ["pastel", "soft", "dreamy", "bright"],
		adjust: { contrast: -18, saturation: -12, exposure: 8, shadows: 10 },
	},
	{
		id: "moody",
		name: "Moody",
		category: "Mood",
		keywords: ["moody", "dark", "cinematic", "dramatic"],
		adjust: { exposure: -18, saturation: -20, contrast: 8, temperature: -8 },
	},
	{
		id: "golden-hour",
		name: "Golden Hour",
		category: "Light",
		keywords: ["golden", "hour", "sunset", "warm"],
		adjust: { temperature: 25, highlights: 15, exposure: 8, saturation: 10 },
	},
	{
		id: "cyberpunk",
		name: "Cyberpunk",
		category: "Color",
		keywords: ["cyberpunk", "neon", "magenta", "futuristic"],
		adjust: { tint: 25, saturation: 20, contrast: 12, temperature: -8 },
	},
	{
		id: "vintage-70s",
		name: "Vintage 70s",
		category: "Film",
		keywords: ["vintage", "70s", "retro", "warm"],
		adjust: { temperature: 15, contrast: -12, saturation: -15, shadows: 12, highlights: -8 },
	},
	{
		id: "clean-bright",
		name: "Clean Bright",
		category: "Light",
		keywords: ["clean", "bright", "air", "commercial"],
		adjust: { exposure: 15, contrast: -8, saturation: 8, shadows: 10 },
	},
	{
		id: "desaturated-drama",
		name: "Desaturated Drama",
		category: "Mood",
		keywords: ["desaturated", "drama", "muted", "serious"],
		adjust: { saturation: -45, contrast: 22, shadows: -8 },
	},
	{
		id: "high-key",
		name: "High Key",
		category: "Light",
		keywords: ["high key", "bright", "airy", "soft"],
		adjust: { exposure: 25, contrast: -15, shadows: 20, saturation: -5 },
	},
];
