// Replaces `virtual:open-slide/slides`.
//
// Upstream generates this module at build time by globbing the slides
// directory and emitting a dynamic `import()` per slide, which Vite compiles on
// demand. The equivalent here is a *static* import map
// (`src/generated/slide-manifest.ts`, regenerated by
// `vendor/build-slide-manifest.mjs`) that the host's esbuild compiles into the
// bundle.
//
// It has to be static. A store app cannot turn a string into code at runtime:
// the project iframe is served with `script-src 'self' 'wasm-unsafe-eval'`, and
// the only `'unsafe-eval'` exception is host-authored, for the bundled Themes
// editor, in unpackaged development builds — spec §4.5 states that every other
// project is ineligible. Importing a `blob:` or `data:` module is refused by
// the same directive. So a slide is compiled when the app is built, not when it
// is opened, and adding one is a source change plus a rebuild rather than a
// runtime action.

import type { SlideModule } from '@/lib/sdk'
import { SLIDE_IDS, SLIDE_MODULES } from '../generated/slide-manifest'
import { readJson, SLIDES_DIR } from '../runtime/store'

type SlideIndex = {
  ids: string[]
  themes: Record<string, string>
  createdAt: Record<string, number>
}

const INDEX_PATH = `${SLIDES_DIR}/.index.json`

// Compiled in, so these are correct before the first render — no async warm-up
// race for the ids themselves.
export let slideIds: string[] = SLIDE_IDS
export let slideThemes: Record<string, string> = {}
export let slideCreatedAt: Record<string, number> = Object.fromEntries(
  SLIDE_IDS.map((id) => [id, 0]),
)

/** Per-slide metadata that users can change (theme assignment, creation order)
 *  still lives in project storage; only the modules are compiled in. */
export async function refreshSlideIndex(): Promise<SlideIndex> {
  const stored = await readJson<Partial<SlideIndex>>(INDEX_PATH, {})
  slideThemes = { ...(stored.themes ?? {}) }
  slideCreatedAt = { ...slideCreatedAt, ...(stored.createdAt ?? {}) }
  return { ids: slideIds, themes: slideThemes, createdAt: slideCreatedAt }
}

export function invalidateSlide(_id: string): void {
  // Nothing to invalidate: a slide is a compiled module for the life of the
  // bundle. Kept so callers written against the runtime-compiled version keep
  // working unchanged.
}

export async function loadSlide(id: string): Promise<SlideModule> {
  const mod = SLIDE_MODULES[id]
  if (!mod) throw new Error(`Slide not found: ${id}`)
  if (!Array.isArray(mod.default)) {
    throw new Error(`Slide ${id} must default-export an array of page components`)
  }
  return mod
}
