#!/usr/bin/env node
// Generates OpenCut's bundled LUT library: ~10 3D `.cube` LUTs written from
// small color transforms. No LUT is downloaded — every value is produced by
// the functions below. Running this script rewrites:
//   app/src/effects/lut/bundled/<id>.cube        (human-readable reference)
//   app/src/effects/lut/bundled-luts.ts           (embedded sources the app loads)
//
// Usage: node app/scripts/generate-luts.mjs
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SIZE = 17;

const clamp01 = (v) => Math.min(1, Math.max(0, v));
const luma = (r, g, b) => 0.2126 * r + 0.7152 * g + 0.0722 * b;

function sCurve(v) {
  return clamp01(0.5 + Math.atan((v - 0.5) * 6) / Math.PI);
}

// Each entry maps an input [r,g,b] (0..1) to an output [r,g,b] (0..1).
const LUTS = [
  {
    id: "teal-orange",
    name: "Teal & Orange",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      return [
        clamp01(r * (1 + 0.12 * l) - 0.06 * (1 - l)),
        clamp01(g),
        clamp01(b * (1 - 0.08 * l) + 0.14 * (1 - l)),
      ];
    },
  },
  {
    id: "warm-film",
    name: "Warm Film",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      return [
        clamp01(r * 1.1 + 0.03 * l),
        clamp01(g * 1.04 + 0.02 * l),
        clamp01(b * 0.88 - 0.02),
      ];
    },
  },
  {
    id: "cool",
    name: "Cool",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      return [
        clamp01(r * 0.9 - 0.02),
        clamp01(g * 0.98),
        clamp01(b * 1.12 + 0.06 * l),
      ];
    },
  },
  {
    id: "bleach-bypass",
    name: "Bleach Bypass",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      const desat = 0.25;
      const r2 = r * (1 - desat) + l * desat;
      const g2 = g * (1 - desat) + l * desat;
      const b2 = b * (1 - desat) + l * desat;
      return [sCurve(r2), sCurve(g2), sCurve(b2)];
    },
  },
  {
    id: "black-and-white",
    name: "Black & White",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      return [l, l, l];
    },
  },
  {
    id: "faded",
    name: "Faded",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      const lift = 0.06;
      const desat = 0.2;
      const r2 = (r - 0.5) * 0.82 + 0.5;
      const g2 = (g - 0.5) * 0.82 + 0.5;
      const b2 = (b - 0.5) * 0.82 + 0.5;
      return [
        clamp01(r2 * (1 - desat) + l * desat + lift),
        clamp01(g2 * (1 - desat) + l * desat + lift),
        clamp01(b2 * (1 - desat) + l * desat + lift),
      ];
    },
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    fn: (r, g, b) => [sCurve(r), sCurve(g), sCurve(b)],
  },
  {
    id: "sepia",
    name: "Sepia",
    fn: (r, g, b) => [
      clamp01(r * 0.393 + g * 0.769 + b * 0.189),
      clamp01(r * 0.349 + g * 0.686 + b * 0.168),
      clamp01(r * 0.272 + g * 0.534 + b * 0.131),
    ],
  },
  {
    id: "cross-process",
    name: "Cross Process",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      return [
        clamp01(r * 1.05 + 0.04 * l),
        clamp01(g * (0.9 + 0.2 * l) + 0.06 * (1 - l)),
        clamp01(b * (1 + 0.1 * (1 - l)) + 0.05 * l),
      ];
    },
  },
  {
    id: "day-for-night",
    name: "Day for Night",
    fn: (r, g, b) => {
      const l = luma(r, g, b);
      const dark = l * 0.45;
      return [
        clamp01(dark * 0.75),
        clamp01(dark * 0.9),
        clamp01(dark * 1.15 + 0.04),
      ];
    },
  },
];

function buildCube(fn) {
  const lines = [];
  lines.push(`# Generated by app/scripts/generate-luts.mjs`);
  lines.push(`LUT_3D_SIZE ${SIZE}`);
  for (let b = 0; b < SIZE; b++) {
    for (let g = 0; g < SIZE; g++) {
      for (let r = 0; r < SIZE; r++) {
        const [ro, go, bo] = fn(r / (SIZE - 1), g / (SIZE - 1), b / (SIZE - 1));
        lines.push(
          `${ro.toFixed(6)} ${go.toFixed(6)} ${bo.toFixed(6)}`,
        );
      }
    }
  }
  return lines.join("\n") + "\n";
}

function buildBundledModule() {
  const entries = LUTS.map(({ id, name, fn }) => {
    const cube = buildCube(fn);
    return { id, name, cube };
  });

  const header = `// Generated by app/scripts/generate-luts.mjs — do not edit by hand.\n`;
  const body = entries
    .map(({ id, name, cube }) => {
      const escaped = cube.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
      return `\t{ id: ${JSON.stringify(id)}, name: ${JSON.stringify(name)}, cube: \`${escaped}\` }`;
    })
    .join(",\n");
  return `${header}export const BUNDLED_LUT_SOURCES = [\n${body},\n];\n`;
}

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, "..");
const bundledDir = resolve(appDir, "src/effects/lut/bundled");
const modulePath = resolve(appDir, "src/effects/lut/bundled-luts.ts");

mkdirSync(bundledDir, { recursive: true });

for (const { id, name, fn } of LUTS) {
  writeFileSync(resolve(bundledDir, `${id}.cube`), buildCube(fn));
  console.log(`wrote ${id}.cube (${name})`);
}

writeFileSync(modulePath, buildBundledModule());
console.log(`wrote ${modulePath}`);
